const STATUS_HTTP_CODE = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER: 500,
};

const ERROR_DETAIL_CODE = {
  EXIST_NAME: 1000,
};

export { STATUS_HTTP_CODE, ERROR_DETAIL_CODE };
